mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('articles/', include('articles.urls')),
    path('internet_shop/', include('internet_shop.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('django_rq/',include('django_rq.urls')),
]

polls/urls.py
from django.urls import path

from . import views

app_name ='polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>', views.detail, name='detail'),
    path('<int:question_id>/vote', views.vote, name="vote"),
    path('<int:question_id>/results', views.results, name="results")
]

polls/models.py
from django.utils import timezone
from django.contrib import admin
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    view_count = models.IntegerField(default=0)

    @admin.display(boolean=True,
                   ordering='pub_date',
                   description='Published_recently?')
    def was_published_recently(self):
        if not self.pub_date:
            return False
        now = timezone.now()
        return now - timezone.timedelta(days=1) <= self.pub_date <= now

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, related_name="choices", on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.question.question_text}:{self.choice_text}'

polls/forms.py
from django import forms
from django.utils import timezone


class QuestionForm(forms.Form):
    question_text = forms.CharField(label="Question", max_length=200)
    publication_date = forms.DateField(initial=timezone.now().date(), widget=forms.SelectDateWidget())
    choices = forms.CharField(label='choices', widget=forms.Textarea)

polls/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.views import generic

from .jobs import add_view_count
from .models import Question
from .forms import QuestionForm



def index(request: HttpResponse):
    questions = Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
    context = {'questions': questions}
    return render(request, 'polls/index.html', context)


def detail(request, question_id: int):
    question = get_object_or_404(Question, id=question_id, pub_date__lte=timezone.now())
    add_view_count.delay(question)
    context = {'question': question}
    return render(request, 'polls/detail.html', context)


def vote(request, question_id: int):
    question = get_object_or_404(Question, id=question_id)
    try:
        selected_choice = question.choices.get(id=request.POST['choice'])
    except (KeyError):
        return render(request, "polls/detail.html", {
            'error_message': "You didn't select a choice",
            'question': question
        })
    selected_choice.votes += 1
    selected_choice.save()
    return redirect('polls:results', question.id)


def results(request, question_id: int):
    question = get_object_or_404(Question, id=question_id)
    context = {'question': question}
    return render(request, 'polls/results.html', context)


def create_question(request):
    if request.method == 'POST':
        form = QuestionForm(request.Post)
        if form.is_valid():
            question_text = form.cleaned_data['question_text']
            publication_date = form.cleaned_data['publication_date']
            question = Question(question_text=question_text, publication_date=publication_date)
            for choice_text in form.cleaned_data['choices'].split('\n'):
                question.choices.create(choice_text=choice_text, votes=0)
            return redirect('polls:detail', question.id)
    else:
        form = QuestionForm()
    return render(request, 'polls/create_question.html', {'form': form})

polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Polls App{% endblock %}</title>

</head>
<body>
    {% block body %}{% endblock %}
</body>
</html>

polls/templates/polls/create_question.html
{% extends 'polls/base.html' %}

{% block body%}
    <form action="{% url 'polls:create' %}" method="post">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" value="Create"/>
    </form>
{% endblock %}

polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="POST">
    {% csrf_token %}
        <h1>{{question.question_text}}</h1>
        <p>&#128065 {{question.view_count}}</p>
        {% if error_message %}
            <p><strong>{{error_message}}</strong></p>
        {% endif %}
        {% for choice in question.choices.all|dictsort:'choice_text' %}
            <input type="radio" name="choice" value="{{choice.id}}"
                id="choice-{{forloop.counter}}"/>
            <label for="choice-{{forloop.counter}}">
                {{choice.choice_text}}
            </label><br>
        {% endfor %}
    <input type="submit" value="vote"/>
</form>

polls/templates/polls/index.html
{% extends 'polls/base.html' %}
{% block body %}
    {% if questions %}
    <h1>Questions:</h1>
        <ul>
            {% for question in questions %}
                <li><a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock %}

polls/templates/polls/results.html
<h1>{{question.question_text}}</h1>
<ul>
    {% for choice in question.choices.all|dictsort:'choice_text' %}
    <li>{{choice.choice_text}} -- {{choice.votes}} vote{{choice.votes|pluralize}}</li>
    {% endfor %}
</ul>