internet_shop/urls.py
from django.urls import path

from . import views


app_name = 'shop'
urlpatterns = [
    path('', views.index, name='index'),
    path('category/<int:category_id>', views.category_detail, name='category_detail'),
    path('products/', views.products_view, name='products'),
    path('product/<int:product_id>', views.product_detail, name='product_detail'),
    path('add_to_cart/', views.add_to_cart, name="add_to_cart"),
    path('my_basket/', views.my_basket, name='my_basket'),
    path('delete_order_entry/', views.delete_order_entry, name='delete_order_entry'),
    path('checkout/', views.checkout, name='checkout'),
    path('personal_account/', views.information_of_user, name='information_of_user'),
    path('edit_information/', views.edit_information, name='edit_information'),
    path('orders_complete/', views.orders_complete, name='orders_complete'),
    path('delete_one_order_entry/', views.delete_one_order_entry, name='delete_one_order_entry'),
    path('edit_count_order_entry/', views.edit_count_order_entry, name="edit_count_order_entry"),
    path('repeat_order/', views.repeat_order, name='repeat_order'),
    path("register/", views.register_request, name="register"),
    path('search/',views.search_products, name='search_products'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('articles/', include('articles.urls')),
    path('internet_shop/', include('internet_shop.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('django_rq/',include('django_rq.urls')),
]

polls/urls.py
from django.urls import path

from . import views

app_name ='polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>', views.detail, name='detail'),
    path('<int:question_id>/vote', views.vote, name="vote"),
    path('<int:question_id>/results', views.results, name="results")
]

internet_shop/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=100)
    image = models.CharField(max_length=1000, blank=True)

    def __str__(self):
        return self.name

    @property
    def count(self):
        count = 0
        category = Category.objects.all()
        for i in category:
            count += 1
        return count


class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.FloatField(default=0.0)
    category = models.ForeignKey(Category, on_delete=models.CASCADE,
                                 related_name='products')
    image = models.CharField(max_length=1000, blank=True)

    def __str__(self):
        return self.name


class OrderEntry(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='+')
    count = models.IntegerField(default=0)
    order = models.ForeignKey('Order', on_delete=models.CASCADE, related_name='order_entries')

    def __str__(self):
        return f'{self.product} - {self.count}'

    @property
    def price(self):
        return self.count * self.product.price


class OrderStatus(models.TextChoices):
    INITIAL = 'INITIAL',
    COMPLETED = 'COMPLETED',
    DELIVERED = 'DELIVERED',


class Order(models.Model):
    profile = models.ForeignKey('Profile', on_delete=models.CASCADE, related_name='orders')
    status = models.CharField(max_length=20, choices=OrderStatus.choices, default=OrderStatus.INITIAL)

    def __str__(self):
        return f'id:{self.id} - {self.profile} - {self.status}'

    @property
    def price(self):
        return sum(order_entry.price for order_entry in self.order_entries.all())

    @property
    def count(self):
        return sum(order_entry.count for order_entry in self.order_entries.all())


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    shopping_cart = models.OneToOneField(Order, on_delete=models.SET_NULL,
                                         null=True, blank=True, related_name='+')

    def __str__(self):
        return str(self.user)

internet_shop/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from django import forms

from internet_shop.models import Profile

User = get_user_model()


# TODO use ModelForm
class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ("username", "first_name", 'last_name', "email")





class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "first_name", 'last_name', "email", "password1", "password2",)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
            Profile.objects.create(user=user)
        return user

internet_shop/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect, HttpRequest
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth import login

from .forms import UserForm, NewUserForm
from .models import Category, Product, Order, OrderStatus


def index(request):
    return render(request, 'shop/index.html', {
        'categories': Category.objects.all(),
    })


def category_detail(request, category_id: int):
    category = get_object_or_404(Category, id=category_id)
    products = Product.objects.filter(category=category)
    paginator = Paginator(products, 9)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'shop/category_detail.html', {
        'category': category, 'page_obj': page_obj,
        'products': products,
    })


def products_view(request):
    products = Product.objects.all()
    paginator = Paginator(products, 9)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'shop/products.html', {
        'products': products, 'page_obj': page_obj,
    })


def product_detail(request, product_id: int):
    return render(request, 'shop/product_detail.html', {
        'product': get_object_or_404(Product, id=product_id),
    })


@login_required()
def add_to_cart(request):
    profile = request.user.profile
    if not profile.shopping_cart:
        profile.shopping_cart = Order(
            profile=request.user.profile)  # т.к связь one to one нужен такой конструктор , для связи где есть релайтет нейм на стороне мени можно обращаться через .create
        profile.shopping_cart.save()
        profile.save()

    assert request.method == "POST"
    product_id = request.POST['product_id']
    product = get_object_or_404(Product, id=product_id)

    order_entry = profile.shopping_cart.order_entries.filter(product=product).first()
    if not order_entry:
        order_entry = profile.shopping_cart.order_entries.create(product=product, count=0)
    order_entry.count += 1
    order_entry.save()
    messages.success(request, 'You are adding product in the basket')
    return redirect('shop:product_detail', product_id)


@login_required()
def my_basket(request):
    profile = request.user.profile
    if not profile.shopping_cart:
        profile.shopping_cart = Order(profile=request.user.profile)
        profile.shopping_cart.save()
        profile.save()
    order_entry = profile.shopping_cart.order_entries.all()
    paginator = Paginator(order_entry, 5)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    all_sum = 0
    for objects in order_entry:
        count = objects.count
        price = objects.product.price
        total = count * price
        all_sum += total
    return render(request, 'shop/my_basket.html', {'order_entry': order_entry, 'all_sum': all_sum,
                                                   'page_obj':page_obj})


def delete_order_entry(request):
    assert request.method == "POST"
    order = request.user.profile.shopping_cart
    order.order_entries.all().delete()
    order.save()
    messages.info(request, "You are cleaning basket right now!")
    return redirect('shop:my_basket')


def checkout(request):
    profile = request.user.profile
    order = profile.shopping_cart
    order.status = OrderStatus.COMPLETED
    order.save()
    profile.shopping_cart = Order.objects.create(profile=profile)
    profile.save()
    messages.success(request, 'Сongratulations your order is paid')
    return redirect('shop:my_basket')


@login_required()
def information_of_user(request: HttpRequest):
    orders = request.user.profile.orders.all().order_by('id').reverse()[:6]
    return render(request, 'shop/personal_account.html', {'orders': orders})


@login_required()
def edit_information(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            user = request.user
            user.username = username
            user.email = email
            user.first_name = first_name
            user.last_name = last_name
            user.save()
            messages.success(request, "You are change information ;)")
            return redirect('shop:information_of_user')
    else:
        form = UserForm(instance=request.user)
    return render(request, 'shop/edit_information.html', {'form': form})


@login_required()
def orders_complete(request):
    orders = request.user.profile.orders.exclude(status='INITIAL').order_by('-id')[:6]
    return render(request, 'shop/orders_complete.html', {'orders': orders})


@login_required()
def delete_one_order_entry(request):
    shopping_cart = request.user.profile.shopping_cart
    shopping_cart.order_entries.get(id=request.POST['objects_id']).delete()
    shopping_cart.save()
    messages.success(request, "Your product delete")
    return redirect('shop:my_basket')


@login_required()
def edit_count_order_entry(request):
    shopping_cart = request.user.profile.shopping_cart.order_entries.get(id=request.POST['objects_id'])
    shopping_cart.count = request.POST['objects_count']
    shopping_cart.save()
    return redirect('shop:my_basket')


@login_required()
def repeat_order(request):
    profile = request.user.profile
    shopping_cart = profile.shopping_cart
    shopping_cart.order_entries.all().delete()
    profile.shopping_cart.save()
    orders = request.user.profile.orders.get(id=request.POST['order_id'])
    for order in orders.order_entries.all():
        profile.shopping_cart.order_entries.create(product=order.product, count=order.count)
        profile.shopping_cart.save()
    profile.save()
    return redirect('shop:my_basket')


def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect('shop:index')
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render(request, "registration/register.html", context={"form": form})


def search_products(request):
    products = Product.objects.filter(name__icontains=request.POST['search'])
    paginator = Paginator(products, 9)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'shop/search.html', {
        'products': products, 'page_obj': page_obj,
    })

## у input text есть values {{в котором можно указать то что будет в строке текст}}

internet_shop/templates/shop/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Shop APP</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>
    body {
      background-image: url('https://plus.unsplash.com/premium_photo-1661434758776-faf568a8a34f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE2fHx8ZW58MHx8fHx8&w=1000&q=80');
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-size: cover;
    }
    </style>
</head>
<body>

    <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a href="{% url 'shop:index' %} " class="navbar-brand" ><span class="glyphicon glyphicon-home"></span> Kingsman </a>
    </div>
      {% if user.is_authenticated %}
    <ul class="nav navbar-nav">
      <li ><a href="{% url 'shop:my_basket' %}"><span class="glyphicon glyphicon-shopping-cart"></span> My basket  {{ user.profile.shopping_cart.count}}</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        <li>
        <form action="{% url 'shop:information_of_user' %}"  method="post">
              {% csrf_token %}
              <input type="submit" value="Profile &#9819;" class="btn btn-default active">
          </form>
        </li>
      <li>
          <form action="{% url 'logout' %}?next={{ request.path }}" method="post">
                {% csrf_token %}
                <input type="submit" value="Logout &#10156;" class="btn btn-danger">
            </form>
      </li>
    </ul>
      {% else %}
        <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'shop:register' %}"><span  class="glyphicon glyphicon-briefcase"></span> Sign Up</a></li>
            <li><a href="{% url 'login' %}?next={{ request.path }}"><span class="glyphicon glyphicon-object-align-bottom"></span> Login</a></li>

      {% endif %}
        </ul>
  </div>
</nav>

    {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <div class="alert alert-success">
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        </div>
                    {% endfor %}
                </ul>
            {% endif %}


    {% block body %}{% endblock %}

</body>
</html>

internet_shop/templates/shop/category_detail.html
{% extends 'shop/base.html' %}

{% block body %}
  <h1 style="font-family:verdana;text-align:center;font-family:verdana;color:Gold;"><p style="font-family:courier;">Category:{{ category.name }}</p></h1>

<div class="row">
    {% for product in page_obj %}
      <div class="col-sm-4">
        <h2 style="font-family:verdana;color:Gold;" class="mt-0">{{product.name}} -- {{product.price}}$</h2>
        <a href="{% url 'shop:product_detail' product.id %}"><img src="{{product.image}}" class="img-thumbnail" alt="Cinque Terre" width="404" height="336"></a>
      </div>
    {% endfor %}
</div>
<nav aria-label="Page navigation example">
      <ul class="pagination">
        {% for p in page_obj.paginator.page_range %}
            <li class="page-item">
                <a href="?page={{p}}" class="page-link">{{p}}</a>
            </li>
        {% endfor %}
      </ul>
</nav>



{% endblock %}

internet_shop/templates/shop/edit_information.html
{% extends 'shop/base.html' %}

{% block body%}

    <form action="{% url 'shop:edit_information'%}" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Apply">
    </form>
{% endblock %}

internet_shop/templates/shop/index.html
{% extends 'shop/base.html' %}
{% block body %}
<style>
input[type=text] {
    width: 100%;
    box-sizing: border-box;
    border: 2px solid #ccc;
    border-radius: 4px;
    font-size: 16px;
    background-color: white;
    background-position: 10px 10px;
    background-repeat: no-repeat;
    padding: 12px 20px 12px 40px;
}
</style>
    {% if not categories %}
        <h1 class="display-1">There are no categories</h1>
    {% else %}
        <div class="bg-1">
          <div class="container text-center">
            <form action="{% url 'shop:search_products' %}" method="post">
                {% csrf_token %}
              <input type="text" name="search" placeholder="Search.." >
            </form>
              <a href="{% url 'shop:products' %}" ><img src="https://i.pinimg.com/originals/a4/53/6c/a4536c9303864b7dcac0e0b2b1e9ac23.jpg" class="img-circle" alt="Bird" width="350" height="350"></a>
            <h3 style="font-family:verdana;color:Gold;">Click!</h3>
          </div>
        </div>

        <div class="container">
          <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
              <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
              <li data-target="#myCarousel" data-slide-to="i" ></li>
              <li data-target="#myCarousel" data-slide-to="2" ></li>
              <li data-target="#myCarousel" data-slide-to="3" ></li>
            </ol>
            <!-- Wrapper for slides -->
            <div class="carousel-inner">
                  <div class="item active">
                    <a href="{% url 'shop:my_basket' %}"><img src="https://s1.1zoom.me/b5050/154/317795-svetik_1920x1200.jpg" alt="Basket" style="width:100%;"></a>
                    <div class="carousel-caption">
                      <h3>Basket</h3>
                        <p class="text-warning">Click me</p>
                    </div>
                  </div>
                {% for category in categories%}
                  <div class="item">
                    <a href="{% url 'shop:category_detail' category.id %}"><img src="{{category.image}}" alt="Products" style="width:100%;"></a>
                    <div class="carousel-caption">
                      <h3>{{category.name}}</h3>
                    </div>
                  </div>
                {% endfor %}
            </div>
              <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
        </div>

    {% endif %}
{% endblock %}

internet_shop/templates/shop/my_basket.html
{% extends 'shop/base.html' %}

{% block body %}

    {% if not order_entry%}
        <h3 style="text-align:center;"><div class="alert alert-danger"><p style="font-family:courier; color:Purple">Your bask is empty!</p></div></h3>
    {% else %}

        <h1 style="font-family:verdana;color:Gold;">Products:</h1>
        {% for objects in page_obj %}
                <h3 style="font-family:verdana;color:White;"><a href="{% url 'shop:product_detail' objects.product.id %}">{{objects.product.name}}</a> -- <span class="badge">{{objects.count}}</span> -- {{objects.price}}$</h3>
                <a href="{% url 'shop:product_detail' objects.product.id %}"><img src="{{objects.product.image}}" class="rounded"  width="304" height="236"></a>
                 <form action="{% url 'shop:edit_count_order_entry' %}" method="post">
                    {% csrf_token %}
                    <input type="text" value={{objects.count}} name="objects_count">
                    <input type="submit" value="Apply">
                    <input type="hidden" value={{objects.id}} name="objects_id">
                </form>
                <form action="{% url 'shop:delete_one_order_entry' %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="delete">
                    <input type="hidden" value={{objects.id}} name="objects_id">
                </form>

        {% endfor %}
        <h3 style="font-family:verdana;color:White;">All sum : <span class="badge">{{all_sum}}$</span></h3>
    <div class="btn-group btn-group-justified">
        <div class="row">
            <form action="{% url 'shop:delete_order_entry' %}" method="post">
                  {% csrf_token %}
                <div class="col-sm-1" style="background-color:active;"><input type="submit" value="Clear basket" class="btn btn-primary btn btn-danger"></div>
            </form>
            <form action="{% url 'shop:checkout' %}" method="post">
                  {% csrf_token %}
                <div class="col-sm-1" style="background-color:active;"><input type="submit" value="Checkout" class="btn btn-primary"></div>
            </form>
    </div>
    {% endif %}
<nav aria-label="Page navigation example">
      <ul class="pagination">
        {% for p in page_obj.paginator.page_range %}
            <li class="page-item">
                <a href="?page={{p}}" class="page-link">{{p}}</a>
            </li>
        {% endfor %}
      </ul>
</nav>


{% endblock %}

internet_shop/templates/shop/orders_complete.html
{% extends 'shop/base.html' %}

{% block body%}
    <div class="row">
    {% for order in orders  %}
        <div class="col-sm-4">
        <h1 style="font-family:verdana;color:Blue">№ order:{{order.id}}</h1>
        {% for order_entry in order.order_entries.all %}
            <h5 style="font-family:verdana;color:Blue"><li>
               Product:{{order_entry.product.name}} -- {{order_entry.count}} -- {{order_entry.price}}
            </li></h5>
        {% endfor %}
        <h4 style="font-family:verdana;color:Blue">Status:{{order.status}}</h4>
        <h4 style="font-family:verdana;color:Blue">Price:{{order.price}}</h4>
        <form action="{% url 'shop:repeat_order' %}" method="post">
                {% csrf_token %}
                <input type="submit" value="Repeat">
                <input type="hidden" value={{order.id}} name="order_id">
        </form>
        </div>
    {% endfor %}
    </div>
        {% if not orders %}
            <h1>There are empty!</h1>
        {% endif %}
{% endblock %}

internet_shop/templates/shop/personal_account.html
{% extends 'shop/base.html' %}

{% block body %}
      <h1 style="text-align:center;font-family:verdana;color:Purple">Profile</h1>
  <div class="row">
        <div class="col-sm-3" style="background-color:active;"><h4 style="font-family:verdana;color:Gold";>Username:{{user.username}}</h4></div>
        <div class="col-sm-3" style="background-color:active;"><h4 style="font-family:verdana;color:Gold";>Email:{{user.email}}</h4></div>
        <div class="col-sm-3" style="background-color:active;"><h4 style="font-family:verdana;color:Gold">First_name:{{user.first_name}}</h4></div>
        <div class="col-sm-2" style="background-color:active;"><h4 style="font-family:verdana;color:Gold">Last_name:{{user.last_name}}</h4></div>
        <h5 style="text-align:mindle"><a href="{% url 'shop:edit_information' %} " class="badge badge-danger">Edit information </a></h5>
  </div>
    {% if orders %}
         <div class="container mt-3">
  <h2><a href="{% url 'shop:orders_complete' %}"> Completing Orders</a></h2>
  <table class="table table-dark table-striped">
    <thead>
      <tr>
        <th style="font-family:verdana;color:Gold">Order Number №</th>
        <th style="font-family:verdana;color:Gold">Count of products</th>
        <th style="font-family:verdana;color:Gold">Order All price</th>
        <th style="font-family:verdana;color:Gold"> Order status</th>
      </tr>
    </thead>
      {% for order in orders %}
    <tbody>
      <tr>
        <td>{{order.id}}</td>
        <td>{{order.count}}</td>
        <td>{{order.price}}</td>
        <td>{{order.status}}</td>
      </tr>


      {% endfor %}
    </tbody>
  </table>
         </div>
    {% else %}
        <p> There are not orders yet </p>
    {% endif %}





{% endblock %}

internet_shop/templates/shop/product_detail.html
{% extends 'shop/base.html' %}

{% block body %}
        <h1 style="text-align:center;"> <p style="font-family:courier; color:MediumSlateBlue">{{ product.name }} </p></h1>
<div class="row">
    <div class="col-sm-4">
    <h1><img src="{{product.image}}" class="rounded" alt="Cinque Terre" width="304" height="236"></h1>
    </div>
</div>
    <h2 style="font-family:verdana;color:White;">Description: {{ product.description }}</h2>
    <h2 style="font-family:verdana;color:White;">Category: <a href="{% url 'shop:category_detail' product.category.id %}">{{ product.category.name }}</a></h2>
    <h2 style="font-family:verdana;color:White;">Price: {{product.price}}$</h2>
     {% if user.is_authenticated %}
    <form action="{% url 'shop:add_to_cart' %}" method="post">
        {% csrf_token %}
      <input type="hidden" name='product_id' value="{{product.id}}">
      <input type="submit" value="ADD PRODUCT" class="btn btn-info">
    </form>
    {% endif %}
{% endblock %}

internet_shop/templates/shop/products.html
{% extends 'shop/base.html' %}

{% block body %}
<h3 style="text-align:center;"><p style="font-family:courier; color:Purple">All Products in shop</p></h3>
    <ul>
        {% for product in page_obj %}
               <div class="well well-sm"><h3><a href="{% url 'shop:product_detail' product.id %}"><p style="color:MediumSlateBlue;">{{ product.name }}</p></a></h3></div>
        {% endfor %}
    </ul>
    <nav aria-label="Page navigation example">
      <ul class="pagination">
        {% for p in page_obj.paginator.page_range %}
            <li class="page-item">
                <a href="?page={{p}}" class="page-link">{{p}}</a>
            </li>
        {% endfor %}
      </ul>
    </nav>
{% endblock %}

internet_shop/templates/shop/search.html
{% extends 'shop/base.html' %}

{% block body %}
    {% if not products %}
        <h1 style="font-family:verdana;text-align:center;font-family:verdana;color:Gold;">This product is not in our store!</h1>
    {% endif %}
    <div class="row">
    {% for product in page_obj %}
        <div class="col-sm-4">
        <h3 style="font-family:verdana;color:Gold;">{{product.name}}</h3>
         <a href="{% url 'shop:product_detail' product.id %}"><img src="{{product.image}}" class="rounded"  width="304" height="236"></a>
        </div>
    {% endfor %}
    </div>
<nav aria-label="Page navigation example">
      <ul class="pagination">
        {% for p in page_obj.paginator.page_range %}
            <li class="page-item">
                <a href="?page={{p}}" class="page-link">{{p}}</a>
            </li>
        {% endfor %}
      </ul>
</nav>


{% endblock %}