articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.main, name='main'),
    path('<int:article_id>', views.title, name='title'),
    path('<int:article_id>/like', views.like, name='like'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('articles/', include('articles.urls')),
    path('internet_shop/', include('internet_shop.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('django_rq/',include('django_rq.urls')),
]

polls/urls.py
from django.urls import path

from . import views

app_name ='polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>', views.detail, name='detail'),
    path('<int:question_id>/vote', views.vote, name="vote"),
    path('<int:question_id>/results', views.results, name="results")
]

articles/models.py
from django.db import models

from django.contrib import admin


class Article(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    author = models.CharField(max_length=20)
    like_count = models.IntegerField(default=0)

    @admin.display(
        boolean=True,
        description="Is popular?",
        ordering='like_count'
    )
    def is_popular(self):
        return self.like_count >= 100

    def __str__(self):
        return self.title

articles/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.template.defaultfilters import pluralize, dictsort
from .models import Article


def main(request: HttpResponse):
    articles = Article.objects.all()
    context = {'articles': articles}
    return render(request, 'articles/main.html', context)


def title(request, article_id: int):
    article = get_object_or_404(Article, id=article_id)
    context = {'article': article}
    return render(request, 'articles/title.html', context)


def like(request, article_id: int):
    article = get_object_or_404(Article, id=article_id)
    like_session = request.session.get("like_object", [])
    if article_id in like_session:
        like_session.remove(article_id)
        article.like_count -= 1
    else:
        like_session.append(article_id)
        article.like_count += 1
    request.session['like_object'] = like_session
    article.save()
    return redirect('articles:title', article.id)

articles/templates/articles/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Artilces {% endblock %}</title>
</head>
<body>
    {% block body %} {% endblock %}
</body>
</html>

articles/templates/articles/like.html
        {% if article.id in favorite_article %}
        <p>Helo World</p>
        {% endif %}
        <h1>Title:{{article.title}}</h1>
        <h3>Author:{{article.author}}</h3>
        <h3>Text:{{article.text}}</h3>
        <p>Like:{{article.like_count}}</p>

articles/templates/articles/main.html
{% extends 'articles/base.html' %}
{% block body %}
    {% if articles %}
    <h1>ALL Articles:</h1>

    <ul>
        {% for article in articles %}
            <li><a href="{% url 'articles:title' article.id %}">{{article.title}}</a></li>
        {% endfor %}
    </ul>
    {% else %}
        <p>There are no articles</p>
    {% endif %}

{% endblock %}

articles/templates/articles/title.html
<form action="{% url 'articles:like' article.id %}" method="POST">
{% csrf_token %}
        {% if article.id in favorite_article %}
        <p>Helo World</p>
        {% endif %}
        <h1>Title:{{article.title}}</h1>
        <h3>Author:{{article.author}}</h3>
        <h3>Text:{{article.text}}</h3>
        <p>Like:{{article.like_count}}</p>
        <input type="submit" value="like" />
        </form>